"""them ai_status cho truc Status (PA1 4.2.9)

Revision ID: 7e173c7cca58
Revises: 2cc3b62627d5
Create Date: 2026-08-07 21:18:52.635764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e173c7cca58'
down_revision: Union[str, Sequence[str], None] = '2cc3b62627d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('ai_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'ai_status')
    # ### end Alembic commands ###
