"""them bang confirmation_requests (PA2 1.3.5)

Revision ID: 81825b585f9c
Revises: 7e173c7cca58
Create Date: 2026-08-08 20:24:26.961962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81825b585f9c'
down_revision: Union[str, Sequence[str], None] = '7e173c7cca58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('confirmation_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_confirmation_requests_conversation_id'), 'confirmation_requests', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_confirmation_requests_status'), 'confirmation_requests', ['status'], unique=False)
    op.create_index(op.f('ix_confirmation_requests_user_id'), 'confirmation_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_confirmation_requests_user_id'), table_name='confirmation_requests')
    op.drop_index(op.f('ix_confirmation_requests_status'), table_name='confirmation_requests')
    op.drop_index(op.f('ix_confirmation_requests_conversation_id'), table_name='confirmation_requests')
    op.drop_table('confirmation_requests')
    # ### end Alembic commands ###
