"""them connected_accounts + subtype (v6 muc 7)

Revision ID: bc4d6abd7c92
Revises: e452d374a43b
Create Date: 2026-08-08 22:56:46.921055

"""
from typing import Sequence, Union

from alembic import op
import uuid
from datetime import datetime, timezone

import sqlalchemy as sa

# Alembic sinh ra `app.core.crypto.EncryptedStr()` trong định nghĩa cột nhưng KHÔNG
# tự thêm import — thiếu dòng này là bản di trú chết ngay với NameError.
import app.core.crypto  # noqa: F401


# revision identifiers, used by Alembic.
revision: str = 'bc4d6abd7c92'
down_revision: Union[str, Sequence[str], None] = 'e452d374a43b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connected_accounts',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('access_token', app.core.crypto.EncryptedStr(), nullable=True),
    sa.Column('refresh_token', app.core.crypto.EncryptedStr(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('account_id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_connected_account_provider_user')
    )
    op.create_index(op.f('ix_connected_accounts_provider'), 'connected_accounts', ['provider'], unique=False)
    op.create_index(op.f('ix_connected_accounts_status'), 'connected_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_connected_accounts_user_id'), 'connected_accounts', ['user_id'], unique=False)
    op.create_table('connected_account_scopes',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['connected_accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', 'scope')
    )
    op.create_table('gmail_accounts',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('history_id', sa.String(), nullable=True),
    sa.Column('watch_expiration', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['connected_accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('outlook_accounts',
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('delta_link', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['connected_accounts.account_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    # ### end Alembic commands ###

    # ── CHUYỂN DỮ LIỆU: sessions → connected_accounts ───────────────────────────
    # Token hộp thư đang nằm trên bảng `sessions`. Không chuyển thì mọi người dùng
    # hiện hữu mất kết nối và phải cấp quyền lại từ đầu.
    #
    # Sinh uuid bằng Python chứ không bằng SQL: hàm sinh uuid của Postgres và SQLite
    # khác nhau, mà bản di trú này phải chạy được trên cả hai (test dựng lại schema
    # từ database trống dùng SQLite).
    conn = op.get_bind()
    phien = conn.execute(sa.text("""
        SELECT s.token, s.user_id, s.expires_at,
               s.google_access_token, s.google_refresh_token, s.google_token_expiry,
               COALESCE(sp.provider, 'google') AS provider,
               u.email
        FROM sessions s
        LEFT JOIN session_providers sp ON sp.token = s.token
        LEFT JOIN users u ON u.id = s.user_id
        WHERE s.google_access_token IS NOT NULL
        ORDER BY s.expires_at DESC
    """)).mappings().all()

    # Mỗi (người, nhà cung cấp) chỉ giữ MỘT kết nối — lấy phiên còn hạn lâu nhất,
    # vì đó là phiên có token mới nhất.
    da_co: set[tuple] = set()
    now = datetime.now(timezone.utc).replace(tzinfo=None)
    for r in phien:
        khoa = (r["user_id"], r["provider"])
        if khoa in da_co:
            continue
        da_co.add(khoa)
        acc_id = uuid.uuid4().hex
        conn.execute(sa.text("""
            INSERT INTO connected_accounts
                (account_id, user_id, provider, provider_user_id, email_address, status,
                 access_token, refresh_token, token_expiry, created_at, updated_at)
            VALUES (:aid, :uid, :prov, :puid, :mail, 'active',
                    :at, :rt, :exp, :now, :now)
        """), {
            "aid": acc_id, "uid": r["user_id"], "prov": r["provider"],
            # Chưa từng lưu id người dùng phía nhà cung cấp — đánh dấu rõ là giá trị
            # tạm để luồng kết nối thật ghi đè sau, và vẫn thoả ràng buộc duy nhất.
            "puid": f"legacy:{r['user_id']}",
            "mail": r["email"] or "",
            "at": r["google_access_token"], "rt": r["google_refresh_token"],
            "exp": r["google_token_expiry"], "now": now,
        })
        bang_con = "gmail_accounts" if r["provider"] != "microsoft" else "outlook_accounts"
        conn.execute(sa.text(f"INSERT INTO {bang_con} (account_id) VALUES (:aid)"),
                     {"aid": acc_id})


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outlook_accounts')
    op.drop_table('gmail_accounts')
    op.drop_table('connected_account_scopes')
    op.drop_index(op.f('ix_connected_accounts_user_id'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_status'), table_name='connected_accounts')
    op.drop_index(op.f('ix_connected_accounts_provider'), table_name='connected_accounts')
    op.drop_table('connected_accounts')
    # ### end Alembic commands ###
