"""chot mailbox_scope_days theo nguoi + index gop audit

Revision ID: e452d374a43b
Revises: 81825b585f9c
Create Date: 2026-08-08 22:23:52.435761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e452d374a43b'
down_revision: Union[str, Sequence[str], None] = '81825b585f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Chỉ mục gộp cho truy vấn thật: "nhật ký của NGƯỜI này, mới nhất trước".
    op.create_index('ix_audit_logs_user_recent', 'audit_logs',
                    ['user_id', sa.literal_column('created_at DESC')], unique=False)

    # Thêm cột theo BA BƯỚC. Thêm thẳng NOT NULL mà không có mặc định thì Postgres từ
    # chối ngay trên bảng đã có dữ liệu — và điền đại 90 cho tất cả thì người đang dùng
    # gói Pro/Pro Max bị thu hẹp phạm vi quét mà không ai báo.
    op.add_column('subscriptions',
                  sa.Column('mailbox_scope_days', sa.Integer(), nullable=True))

    # Điền theo ĐÚNG gói mà mỗi người đang dùng.
    op.execute("""
        UPDATE subscriptions SET mailbox_scope_days = CASE tier
            WHEN 'pro' THEN 180
            WHEN 'max' THEN 365
            ELSE 90
        END
    """)

    # batch_alter_table: SQLite không có ALTER COLUMN, Alembic sẽ dựng lại bảng.
    # Postgres thì chạy ALTER bình thường. Dùng cách này để bản di trú chạy được
    # trên CẢ HAI — test dựng lại schema từ database trống dùng SQLite.
    with op.batch_alter_table('subscriptions') as batch:
        batch.alter_column('mailbox_scope_days',
                           existing_type=sa.Integer(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'mailbox_scope_days')
    op.drop_index('ix_audit_logs_user_recent', table_name='audit_logs')
    # ### end Alembic commands ###
